<?php

namespace Acme\EntidadReceptoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntidadReceptoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadReceptoraRepository extends EntityRepository
{
}
