<?php

namespace Acme\EntidadReceptoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoEntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEntidadRepository extends EntityRepository
{
}
