<?php

namespace Acme\EntidadReceptoraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioPrestadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioPrestadoRepository extends EntityRepository
{
}
