<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/10 21:30:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=BancoAlimentarioPromocion',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
