<?php

namespace Acme\AlimentoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentoRepository extends EntityRepository
{
}
