<?php

namespace Acme\AlimentoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleAlimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleAlimentoRepository extends EntityRepository
{
}
