<?php

namespace Acme\DonanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonanteRepository extends EntityRepository
{
}
