<?php

namespace Acme\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlimentoEntregaDirectaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentoEntregaDirectaRepository extends EntityRepository
{
}
