<?php

namespace Acme\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TurnoEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoEntregaRepository extends EntityRepository
{
}
